#!/bin/sh
# Copy current state of all files into the repo
cp ~/.zshrc .zshrc
cp ~/.zprofile .zprofile
cp ~/.p10k.zsh .p10k.zsh
cp "/Users/kal/Library/Application Support/Code/User/settings.json" .vscode/user-settings.json